# Dependency Review Action
#
# This Action will scan dependency manifest files that change as part of a Pull Request, surfacing known-vulnerable versions of the packages declared or updated in the PR. Once installed, if the workflow run is marked as required, PRs introducing known-vulnerable packages will be blocked from merging.
#
# Source repository: https://github.com/actions/dependency-review-action
# Public documentation: https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/about-dependency-review#dependency-review-enforcement
name: 'Dependency Review'
on: [pull_request]

permissions:
  contents: write
  pull-requests: write

jobs:
  dependency-review:
    runs-on: windows-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3
      # Use github context vars https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables
      - name: Refs
        run: |        
          echo "ref: ${{ github.ref }}"
          echo "base ref: ${{ github.base_ref }}"
          echo "head ref: ${{ github.head_ref }}"
      # This is executed in component-detection.yml on every push (also on PR!)
      #- run: nuget restore .\Fsharp-WebAPI.sln
      #- name: Component detection 
      #  uses: advanced-security/component-detection-dependency-submission-action@v0.0.2
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v3
        with: 
          retry-on-snapshot-warnings: true
          retry-on-snapshot-warnings-timeout: 240 #default 120 was not long enough for nuget restore to complete (alternative would be to run this in same PR workflow and exclude from generic push)
          comment-summary-in-pr: true
          # fail on any copy left license types
          deny-licenses: GPL-2.0, GPL-3.0, LGPL-2.0, LGPL-3.0, AGPL-1.0, AGPL-1.0-only, AGPL-1.0-or-later, AGPL-3.0, AGPL-3.0-only, AGPL-3.0-or-later, RPL-1.1, RPL-1.5, RPSL-1.0, OCLC-2.0, NGPL, ODbL-1.0, MS-RL, OSL-1.0, OSL-1.1, OSL-2.0, OSL-2.1, OSL-3.0, MPL-2.0, MPL-1.0, MPL-1.1, MPL-2.0-no-copyleft-exception, EPL-1.0, EPL-2.0
          #fail-on-severity: moderate
